/**
 * Below are the colors that are used in the app. The colors are defined in the light and dark mode.
 * There are many other ways to style your app. For example, [Nativewind](https://www.nativewind.dev/), [Tamagui](https://tamagui.dev/), [unistyles](https://reactnativeunistyles.vercel.app), etc.
 */

import '@/global.css';

import { Platform } from 'react-native';

export const Colors = {
  light: {
    // ── 1:1 aus style.css der notenlern-app (Light) ──
    bgBody: '#1a1a2e',
    bgSurface: '#f5f0eb',
    bgSurfaceAlt: '#f8f9fa',
    bgCard: '#ffffff',
    bgModal: '#ffffff',
    bgHeader: '#2d2d44',
    bgInput: '#f8f9fa',
    bgHover: '#f0f0f0',
    textPrimary: '#333333',
    textSecondary: '#555555',
    textTertiary: '#666666',
    textMuted: '#999999',
    textOnHeader: '#e8e4e0',
    textOnAccent: '#ffffff',
    textHeading: '#2d2d44',
    border: '#dddddd',
    borderStrong: '#999999',
    borderInput: '#dddddd',
    accent: '#2d2d44',
    accentHover: '#3d3d5c',
    accentBlue: '#4a90e2',
    accentBlueBg: '#e3f2fd',
    accentBlueHover: '#357abd',
    accentLight: '#9a9abb',
    noteBadgeBg: '#2d2d44',
    noteBadgeText: '#e8e4e0',
    parchment: '#fdf6e3',
    parchmentFiber1: '#c4a35a',
    parchmentFiber2: '#b8976a',
    staffLine: '#000000',
    noteHead: '#000000',
    clef: '#000000',
    staffBg: '#ffffff',
    btnSecondaryBg: '#ffffff',
    btnSecondaryText: '#2d2d44',
    btnSecondaryBorder: '#2d2d44',
    cardBg: '#ffffff',
    cardBorder: '#dddddd',
    cardTitle: '#333333',
    cardDesc: '#666666',
    errorBg: '#f5f5f5',
    errorTextBg: '#fee2e2',
    errorTextColor: '#dc2626',
    successBg: '#dcfce7',
    successText: '#16a34a',
    warningBg: '#fef3c7',
    warningText: '#92400e',
    closeBtnHover: '#f0f0f0',
    closeBtnText: '#999999',
    statValue: '#2d2d44',
    statLabel: '#666666',
    headerBtnBg: 'rgba(255, 255, 255, 0.1)',
    headerBtnBorder: 'rgba(255, 255, 255, 0.15)',
    headerBtnText: '#cccccc',
    headerBtnHover: 'rgba(255, 255, 255, 0.2)',
    headerBtnActiveBg: 'rgba(255, 255, 255, 0.9)',
    headerBtnActiveText: '#2d2d44',
    speechExampleBg: '#f0eee8',
    speechExampleText: '#4b5563',
    rfCardBg: '#ffffff',
    progressBg: '#e0e0e0',
    timerBg: '#e0e0e0',
    hintBg: '#fff3cd',
    hintBorder: '#ffc107',
    hintText: '#856404',
    btnNoteBg: '#2d2d44',
    btnNoteText: '#ffffff',
    btnNoteBorder: '#2d2d44',
    keyboardBg: '#1a1a1a',
    // Legacy-Aliasse
    text: '#333333',
    background: '#f5f0eb',
    backgroundElement: '#f8f9fa',
    backgroundSelected: '#e3f2fd',
  },
  dark: {
    // ── 1:1 aus style.css der notenlern-app ([data-theme="dark"]) ──
    bgBody: '#0f0f1a',
    bgSurface: '#1a1a2e',
    bgSurfaceAlt: '#222240',
    bgCard: '#ffffff',
    bgModal: '#ffffff',
    bgHeader: '#12121f',
    bgInput: '#252545',
    bgHover: '#2a2a48',
    textPrimary: '#e0dcd8',
    textSecondary: '#b0aaa4',
    textTertiary: '#9a9490',
    textMuted: '#706a64',
    textOnHeader: '#d8d4d0',
    textOnAccent: '#ffffff',
    textHeading: '#c8c4c0',
    border: '#3a3a55',
    borderStrong: '#505070',
    borderInput: '#3a3a55',
    accent: '#3d3d60',
    accentHover: '#4d4d70',
    accentBlue: '#5a9ae8',
    accentBlueBg: '#1a2a44',
    accentBlueHover: '#4a8ad8',
    accentLight: '#8888aa',
    noteBadgeBg: '#2a2a48',
    noteBadgeText: '#e0dcd8',
    parchment: '#1e1e32',
    parchmentFiber1: '#3a3a55',
    parchmentFiber2: '#333350',
    staffLine: '#e0e0e0',
    noteHead: '#e0e0e0',
    clef: '#d0d0d0',
    staffBg: '#1e1e32',
    btnSecondaryBg: '#252545',
    btnSecondaryText: '#d0ccc8',
    btnSecondaryBorder: '#4a4a6a',
    cardBg: '#1e1e34',
    cardBorder: '#3a3a55',
    cardTitle: '#e0dcd8',
    cardDesc: '#9a9490',
    errorBg: '#222240',
    errorTextBg: '#3a1a1a',
    errorTextColor: '#f87171',
    successBg: '#1a2e1a',
    successText: '#4ade80',
    warningBg: '#2e2a1a',
    warningText: '#fbbf24',
    closeBtnHover: '#2a2a48',
    closeBtnText: '#706a64',
    statValue: '#d0ccc8',
    statLabel: '#9a9490',
    headerBtnBg: 'rgba(255, 255, 255, 0.08)',
    headerBtnBorder: 'rgba(255, 255, 255, 0.12)',
    headerBtnText: '#aaaaaa',
    headerBtnHover: 'rgba(255, 255, 255, 0.15)',
    headerBtnActiveBg: 'rgba(255, 255, 255, 0.85)',
    headerBtnActiveText: '#1a1a2e',
    speechExampleBg: '#252545',
    speechExampleText: '#b0aaa4',
    rfCardBg: '#1e1e34',
    progressBg: '#3a3a55',
    timerBg: '#3a3a55',
    hintBg: '#332a10',
    hintBorder: '#6b5a20',
    hintText: '#d4b860',
    btnNoteBg: '#3a3a60',
    btnNoteText: '#e0dcd8',
    btnNoteBorder: '#4a4a6a',
    keyboardBg: '#0a0a12',
    // Legacy-Aliasse
    text: '#e0dcd8',
    background: '#1a1a2e',
    backgroundElement: '#222240',
    backgroundSelected: '#1a2a44',
  },
} as const;

export type ThemeColor = keyof typeof Colors.light & keyof typeof Colors.dark;

export const Fonts = Platform.select({
  ios: {
    /** iOS `UIFontDescriptorSystemDesignDefault` */
    sans: 'system-ui',
    /** iOS `UIFontDescriptorSystemDesignSerif` */
    serif: 'ui-serif',
    /** iOS `UIFontDescriptorSystemDesignRounded` */
    rounded: 'ui-rounded',
    /** iOS `UIFontDescriptorSystemDesignMonospaced` */
    mono: 'ui-monospace',
  },
  default: {
    sans: 'normal',
    serif: 'serif',
    rounded: 'normal',
    mono: 'monospace',
  },
});

export const Spacing = {
  half: 2,
  one: 4,
  two: 8,
  three: 16,
  four: 24,
  five: 32,
  six: 64,
} as const;

/**
 * Reserve für die (entfernte) Tab-Bar. Die App nutzt seit dem Umbau auf ein
 * reines Stack-Layout keine Tab-Bar mehr — alle Screens laufen über Home-Karten.
 * Der Wert bleibt als Slot erhalten, falls später wieder eine Bar ergänzt wird.
 */
export const BottomTabInset = 0;
export const MaxContentWidth = 800;
